[package]
name = "excursor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
aws-config = "1.8.13"
aws-sdk-s3 = "1.122.0"
burn = { version = "0.20.0", features = ["fusion", "std", "train", "tui", "wgpu"] }
clap = { version = "4.6.1", features = ["derive"] }
splintr = { version = "0.8.0", features = ["python"] }
tokio = { version = ">=1.49.0", features = ["full"] }
