[workspace]
authors = ["Sean Toner <placeoftheway@gmail.com>"]
channels = ["conda-forge"]
name = "excursor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fmt = "autopep8 -i -r ."
lint = "ruff check --fix ."

[dependencies]
python = "3.13.*"
rust = ">=1.92.0,<1.93"
loguru = ">=0.7.3,<0.8"

[feature.dev.dependencies]
autopep8 = "*"
ruff = "*"

[feature.test.dependencies]
pytest = "*"
pytest-asyncio = "*"

[environments]
dev = ["dev"]
test = ["test"]
