[project]
name = "excursor"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["linux-64"]

[tasks]
lint = "ruff check --fix ."

[dependencies]
python = ">=3.12.2,<3.13"
numpy = ">=1.26.4,<1.27"
sympy = ">=1.12,<2"
httpx = ">=0.28.0,<0.29"
pydantic = ">=2.7.1"
ipywidgets = ">=8.1.2,<8.2"
jupyterlab = ">=4.1.5,<4.2"
holoviews = ">=1.18.3,<1.19"
pytest = "*"
ruff = "*"
autopep8 = "*"
pytest-asyncio = "*"
modular = ">=25.5.0.dev2025071105,<26"

[pypi-dependencies]
daak = "*"
