[project]
name = "excursor"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sean Toner <placeoftheway@gmail.com>"]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]
fmt = "autopep8 -i ."
lint = "ruff check . --fix"
test = "pytest tests -rA -s"
check = {depends-on = ["fmt", "lint", "test"]}
git-add = "git add ."
commit = {cmd = "git commit -m ", depends-on = ["check", "git-add"]}
push = "git push origin "

[pypi-options]
index-url = "https://pypi.python.org/simple"
extra-index-urls = ["https://download.pytorch.org/whl/cu124"]

[dependencies]
python = ">=3.12.2,<3.13"
sympy = ">=1.12,<2"
httpx = ">=0.28.0,<0.29"
fastapi = ">=0.115.0,<0.119.0"
uvicorn = ">=0.34.0,<0.40"
pydantic = ">=2.7.4,<2.8"
pytest = ">=8.2.2,<8.5"
autopep8 = ">=2.3.1,<3"
ruff = ">=0.9.0,<0.10.0"
jupyterlab = ">=4.2.4,<5"
ipywidgets = ">=8.1.5,<9"
transformers = ">=4.44.2,<5"
tqdm = ">=4.66.5,<5"
pytorch = ">=2.2.2,<3"
pytorch-cuda = ">=11.8,<12"


[pypi-dependencies]
daak = "*"
getdaft = { version = "*", extras = ["aws"] }
chardet = ">=5.2.0, <6"
pyyaml = "*"
ray = { version = ">=2.41.0, <3", extras = ["default"] }
pillow = ">=11.0.0, <12"
pymc = ">=5.21.1, <6"
# bambi = ">=0.15.0, <0.16"
# pymc-bart = ">=0.5.1, <0.6"
# kulprit = ">=0.3.0, <0.4"
# nutpie = ">=0.13.3, <0.14"

